# Generated by Django 5.2.4 on 2025-07-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('enqueteur', 'Enquêteur'), ('juge', 'Juge'), ('invite', 'Invité'), ('admin', 'Administrateur')], default='invite', max_length=20),
        ),
    ]
