# Generated by Django 5.1.4 on 2025-07-03 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capture', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capturesession',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prediction',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='capture.capturesession'),
        ),
        migrations.AddField(
            model_name='zeeklog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capture.capturesession'),
        ),
        migrations.AddIndex(
            model_name='zeeklog',
            index=models.Index(fields=['log_type'], name='capture_zee_log_typ_47a747_idx'),
        ),
        migrations.AddIndex(
            model_name='zeeklog',
            index=models.Index(fields=['timestamp'], name='capture_zee_timesta_ed2a5b_idx'),
        ),
    ]
