# Generated by Django 5.2.4 on 2025-07-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0003_prediction_dst_ip_prediction_src_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturesession',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
